#!/bin/bash

source /etc/my_init.d/include/gitit

if [[ "${MY_DEBUG}" = 1 ]]; then
  source /etc/my_init.d/include/debug
else
  source /etc/my_init.d/include/no_debug
fi

BASE_DIR="${GITIT_DIR}"
USER="${GITIT_USER}"
GROUP="${GITIT_GROUP}"
BINENV="${GITIT_BINENV}"

cd "${BASE_DIR}" || exit 1

if [[ -d "${BASE_DIR}/var/cache" ]]; then
  rm -rf "${BASE_DIR}/var/cache/*"
fi

exec chpst -u "${USER}:${GROUP}" -e "${BINENV}" \
  gitit -f "${BASE_DIR}/etc/gitit.conf"

